#!/usr/bin/env python3
"""
Build the Hackathon Data Asset Register (.xlsx) across all five challenges.

    python scripts/build-data-register.py --out "<path>/IF-R1X_Hackathon_Data_Register.xlsx"
    python scripts/build-data-register.py --check      # read-only drift check, exits non-zero

STANDARDS THIS IMPLEMENTS
    DAMA-DMBOK2        governance roles, metadata management, data quality dimensions
    ISO/IEC 11179      metadata registry structure (Data Dictionary sheet)
    ISO/IEC 20889      de-identification terminology and technique classification
    ISO/IEC 25012      data quality model
    ISO/IEC 27001/27701 security and privacy information management
    ISO 31000          risk register structure
    UK GDPR Art 30     record of processing activities
    ICO anonymisation guidance / DPA 2018
    Government Data Quality Framework
    Open Government Licence v3.0 (attribution obligations)

THE DRIFT PROBLEM, AND HOW THIS HANDLES IT
    Derived sheets (Control, Asset Register, Data Dictionary, De-identification,
    Licence & Attribution) are REGENERATED every run from catalogue/*.yml and build
    evidence. They are evidence of what the pipeline actually did, and hand-edited
    evidence drifts from reality — which is the first thing an auditor tests.

    Judgement sheets (ROPA, Data Quality, Roles, Risk Register, Change Log) hold
    decisions no YAML can express — a lawful basis, a risk rating, a named owner.
    They are READ AND PRESERVED verbatim on regeneration, in the same spirit as
    build-backlog.py's --add-new.

    This differs from the compliance-backlog workbook, where Excel is master. That
    is deliberate and is flagged as Q8 in the compliance design for confirmation.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from datetime import date
from pathlib import Path

try:
    import yaml
    from openpyxl import Workbook, load_workbook
    from openpyxl.styles import Alignment, Font, PatternFill
    from openpyxl.utils import get_column_letter
    from openpyxl.worksheet.table import Table, TableStyleInfo
except ImportError:  # pragma: no cover
    sys.exit("Install deps first: pip install pyyaml openpyxl")

REPO = Path(__file__).resolve().parent.parent
CATALOGUE = REPO / "catalogue"

DERIVED = ["Control", "Asset Register", "Data Dictionary", "De-identification", "Licence & Attribution"]
PRESERVED = ["ROPA", "Data Quality", "Roles", "Risk Register", "Change Log"]

HDR_FILL = PatternFill("solid", fgColor="1D1F20")
HDR_FONT = Font(color="FFFFFF", bold=True, size=10)
TITLE_FONT = Font(bold=True, size=13)
NOTE_FONT = Font(italic=True, size=9, color="595959")
WARN_FILL = PatternFill("solid", fgColor="FFF2CC")


def sheet(wb: Workbook, name: str, title: str, note: str, headers: list[str], rows: list[list]):
    ws = wb.create_sheet(name)
    ws["A1"] = title
    ws["A1"].font = TITLE_FONT
    ws["A2"] = note
    ws["A2"].font = NOTE_FONT
    ws.merge_cells(start_row=2, start_column=1, end_row=2, end_column=max(len(headers), 4))
    ws["A2"].alignment = Alignment(wrap_text=True, vertical="top")
    ws.row_dimensions[2].height = 30

    hr = 4
    for c, h in enumerate(headers, 1):
        cell = ws.cell(row=hr, column=c, value=h)
        cell.fill, cell.font = HDR_FILL, HDR_FONT
        cell.alignment = Alignment(wrap_text=True, vertical="center")
    for r, row in enumerate(rows, hr + 1):
        for c, v in enumerate(row, 1):
            cell = ws.cell(row=r, column=c, value=v)
            cell.alignment = Alignment(wrap_text=True, vertical="top")

    if rows:
        ref = f"A{hr}:{get_column_letter(len(headers))}{hr + len(rows)}"
        t = Table(displayName=name.replace(" ", "").replace("&", ""), ref=ref)
        t.tableStyleInfo = TableStyleInfo(name="TableStyleLight1", showRowStripes=True)
        ws.add_table(t)

    for c, h in enumerate(headers, 1):
        longest = max([len(str(h))] + [len(str(r[c - 1])) for r in rows if r[c - 1] is not None] or [10])
        ws.column_dimensions[get_column_letter(c)].width = min(max(longest + 2, 12), 58)
    ws.freeze_panes = ws.cell(row=hr + 1, column=1)
    return ws


def load_catalogues() -> list[dict]:
    out = []
    for p in sorted(CATALOGUE.glob("*.yml")):
        if p.stem.startswith("_"):
            continue
        with p.open() as fh:
            c = yaml.safe_load(fh)
        c["_file"] = p.name
        c["_sha"] = hashlib.sha256(p.read_bytes()).hexdigest()[:12]
        out.append(c)
    return out


def build(cats: list[dict], evidence: dict, preserved: dict[str, list[list]]) -> Workbook:
    wb = Workbook()
    wb.remove(wb.active)
    today = date.today().isoformat()

    # ---------------- 1. Control ----------------
    sheet(
        wb, "Control", "Hackathon Data Asset Register — Control",
        "Generated by scripts/build-data-register.py. Derived sheets are regenerated every run and "
        "must not be hand-edited; judgement sheets are preserved verbatim. See the compliance design §G.",
        ["Item", "Value"],
        [
            ["Product", "Innovation Forum × R1X hackathon data platform"],
            ["Covers", f"{len(cats)} challenge(s): " + ", ".join(c["challenge"] for c in cats)],
            ["Data controller", "Innovation Forum"],
            ["Technology partner (processor)", "R1X — Art 28 agreement REQUIRED, see compliance design §C"],
            ["Contact", "info@inno-forum.co.uk"],
            ["Generated", today],
            ["Review cycle", "Per release, and at each quarterly product review"],
            ["", ""],
            ["— Standards —", ""],
            ["DAMA-DMBOK2", "Governance roles, metadata, data quality dimensions"],
            ["ISO/IEC 11179", "Metadata registry — Data Dictionary sheet"],
            ["ISO/IEC 20889", "De-identification terminology and techniques"],
            ["ISO/IEC 25012", "Data quality model"],
            ["ISO/IEC 27001 / 27701", "Information security / privacy information management"],
            ["ISO 31000", "Risk management"],
            ["UK GDPR Art 30", "Record of processing activities (ROPA sheet)"],
            ["DPA 2018 + ICO anonymisation guidance", "'Means reasonably likely to be used' test"],
            ["Government Data Quality Framework", "Quality dimensions for public-sector data"],
            ["Open Government Licence v3.0", "Attribution obligations per source"],
            ["", ""],
            ["— Sheet types —", ""],
            ["DERIVED (regenerated)", ", ".join(DERIVED)],
            ["PRESERVED (human judgement)", ", ".join(PRESERVED)],
        ],
    )

    # ---------------- 2. Asset Register ----------------
    rows = []
    for c in cats:
        for t in c.get("gold_tables", []):
            individuals = bool(t.get("contains_individuals"))
            rows.append([
                c["challenge"], c.get("title"), t["name"], "gold",
                t.get("description"), t.get("grain"), t.get("approx_rows"),
                "Personal data" if individuals else "Non-personal",
                "Yes" if individuals else "No",
                "Public" if not individuals else "Restricted until DPIA",
                "Innovation Forum", "TBC — see Roles",
                "Blocked: " + t["blocked_by"] if t.get("blocked_by") else "Planned",
                c["_file"], c["_sha"],
            ])
    sheet(
        wb, "Asset Register", "Data Asset Register (DMBOK / ISO 11179)",
        "One row per published table across all challenges. Derived from catalogue/*.yml — regenerated each run.",
        ["Challenge", "Challenge title", "Table", "Layer", "Description", "Grain", "Approx rows",
         "Data classification", "Contains individuals", "Publication status", "Controller",
         "Data steward", "Build status", "Source catalogue", "Catalogue SHA"],
        rows,
    )

    # ---------------- 3. Data Dictionary ----------------
    rows = []
    for c in cats:
        for t in c.get("gold_tables", []):
            qids = t.get("quasi_identifiers") or []
            gen = t.get("generalisation") or {}
            for q in qids:
                rows.append([
                    c["challenge"], t["name"], q, "Quasi-identifier", "string",
                    "Contributes to re-identification risk when combined with other QIs",
                    "Yes", "No", gen.get(q, "—"),
                    "ISO/IEC 11179 · ISO/IEC 20889",
                ])
            if not qids:
                rows.append([
                    c["challenge"], t["name"], "(no quasi-identifiers declared)", "—", "—",
                    "Table does not describe individuals", "No", "No", "—", "ISO/IEC 11179",
                ])
    sheet(
        wb, "Data Dictionary", "Data Element Dictionary (ISO/IEC 11179)",
        "Column-level metadata. Quasi-identifiers are a HUMAN judgement recorded in the catalogue, "
        "never inferred by tooling — they encode what the data could realistically be linked against.",
        ["Challenge", "Table", "Element", "Role", "Datatype", "Definition",
         "Quasi-identifier", "Direct identifier", "Generalises to", "Standard"],
        rows,
    )

    # ---------------- 4. ROPA (preserved) ----------------
    ropa = preserved.get("ROPA") or [
        [c["challenge"], c.get("title"),
         "Publish open data for a public hackathon challenge",
         "Art 6(1)(f) legitimate interests — LIA REQUIRED",
         ("Art 9(2)(j) research + DPA 2018 Sch 1 Pt 1 para 4 — CONFIRM"
          if (c.get("sensitivity") or {}).get("personal_data") else "n/a"),
         "Councillors (public office holders)" if (c.get("sensitivity") or {}).get("personal_data") else "None",
         "Hackathon participants (public)", "Immutable public release — see retention note",
         "GitHub (US), Cloudflare (US) — transfer assessment REQUIRED",
         "TBC", "Not started"]
        for c in cats
    ]
    ws = sheet(
        wb, "ROPA", "Record of Processing Activities (UK GDPR Art 30)",
        "HUMAN JUDGEMENT — preserved across regeneration. A lawful basis is a decision, not a derived value. "
        "Rows are seeded once with TBC placeholders; complete them and they will be retained.",
        ["Challenge", "Title", "Purpose", "Lawful basis (Art 6)", "Special category condition (Art 9)",
         "Data subjects", "Recipients", "Retention", "International transfers", "DPIA reference", "Status"],
        ropa,
    )
    ws["A2"].fill = WARN_FILL

    # ---------------- 5. De-identification ----------------
    rows = []
    for c in cats:
        for t in c.get("gold_tables", []):
            if not t.get("contains_individuals"):
                continue
            ev = evidence.get(f"{c['challenge']}/{t['name']}", {})
            rows.append([
                c["challenge"], t["name"],
                "Anonymisation (irreversible) — no surrogate map retained",
                ", ".join(t.get("quasi_identifiers") or []),
                t.get("k_threshold"), ev.get("k_achieved", "not yet measured"),
                ev.get("technique", "not yet run"),
                ev.get("rows_generalised", "—"), ev.get("rows_suppressed", "—"),
                ev.get("l_diversity_min", "not measured"),
                "PASS" if ev.get("passed") else "NOT EVIDENCED",
                ev.get("date", "—"), "TBC", "ISO/IEC 20889",
            ])
    sheet(
        wb, "De-identification", "De-identification & k-anonymity (ISO/IEC 20889)",
        "Evidence that the anonymisation claim holds. The gold layer is published as ANONYMISED — no "
        "surrogate mapping survives a build — so k-anonymity, not name removal, is what earns that claim. "
        "Populated from build output; 'NOT EVIDENCED' means the table must not be published.",
        ["Challenge", "Table", "Technique", "Quasi-identifiers", "k threshold", "k achieved",
         "Method applied", "Rows generalised", "Rows suppressed", "l-diversity (min)",
         "Result", "Assessed", "Signed off by", "Standard"],
        rows,
    )

    # ---------------- 6. Data Quality (preserved) ----------------
    dq = preserved.get("Data Quality") or [
        [c["challenge"], t["name"], dim, target, "not measured", "TBC", "ISO/IEC 25012 · GDQF"]
        for c in cats for t in c.get("gold_tables", [])
        for dim, target in [("Completeness", "≥ 95% non-null on required columns"),
                            ("Accuracy", "Matches publisher source on sampled rows"),
                            ("Consistency", "Schema matches datapackage.json"),
                            ("Currentness", "Source refreshed within declared cadence"),
                            ("Credibility", "Named public-sector publisher")]
    ]
    ws = sheet(
        wb, "Data Quality", "Data Quality (ISO/IEC 25012 · Government Data Quality Framework)",
        "HUMAN JUDGEMENT — preserved across regeneration. Thresholds are a decision about fitness for purpose.",
        ["Challenge", "Table", "Dimension", "Target", "Measured", "Assessed by", "Standard"], dq,
    )
    ws["A2"].fill = WARN_FILL

    # ---------------- 7. Licence & Attribution ----------------
    rows = []
    for c in cats:
        for s in c.get("sources", []):
            redis = s.get("redistributable") is True
            rev = s.get("licence_reviewed") is True
            rows.append([
                c["challenge"], s["id"], s.get("name"), s.get("publisher"), s.get("licence"),
                "Yes" if redis else "No", "Yes" if rev else "No",
                "Mirrored" if (redis and rev) else "Pointer + loader only",
                c.get("attribution") or "—", s.get("url"),
            ])
    sheet(
        wb, "Licence & Attribution", "Licence & Attribution (OGL v3.0 and others)",
        "OGL attribution is a LICENCE CONDITION — omitting it makes republication an infringement, "
        "not a discourtesy. 'Pointer + loader only' rows are never mirrored by us.",
        ["Challenge", "Source ID", "Source", "Publisher", "Licence", "Redistributable",
         "Licence reviewed", "Treatment", "Attribution text", "URL"], rows,
    )

    # ---------------- 8. Roles (preserved) ----------------
    roles = preserved.get("Roles") or [
        ["Data Owner", "TBC", "Innovation Forum", "Accountable for the data asset and its publication", "DMBOK"],
        ["Data Steward", "TBC", "Innovation Forum", "Defines quasi-identifiers, quality thresholds, definitions", "DMBOK"],
        ["Data Custodian", "TBC", "R1X", "Operates pipeline and hosting — processor under Art 28", "DMBOK"],
        ["Data Protection Officer / adviser", "TBC", "Innovation Forum", "DPIA, LIA, Art 14 notice, ICO liaison", "UK GDPR"],
        ["SIRO / senior risk owner", "TBC", "Innovation Forum", "Accepts residual risk", "ISO 27001"],
        ["Safeguarding lead", "TBC", "Innovation Forum", "Challenges 04 and 05", "Programme"],
    ]
    ws = sheet(
        wb, "Roles", "Roles & Accountabilities (DAMA-DMBOK2)",
        "HUMAN JUDGEMENT — preserved across regeneration. Every 'TBC' is an unassigned accountability.",
        ["Role", "Name", "Organisation", "Responsibility", "Standard"], roles,
    )
    ws["A2"].fill = WARN_FILL

    # ---------------- 9. Risk Register (preserved) ----------------
    risks = preserved.get("Risk Register") or [
        ["R01", "Re-identification of a councillor from quasi-identifiers", "Privacy", "Possible", "Major", "High",
         "k-anonymity gate (k≥5) + generalisation; build fails below threshold", "Low", "TBC", "Open"],
        ["R02", "Inferring a Localism Act s.32 withheld sensitive interest", "Privacy / safety", "Unlikely", "Severe", "High",
         "Explicit prohibition in challenge rules; no cross-source linkage of registers", "Low", "TBC", "Open"],
        ["R03", "Publishing data without a completed DPIA", "Legal", "Possible", "Major", "High",
         "Build gate fails on personal_data: true until DPIA reference recorded", "Low", "TBC", "Open"],
        ["R04", "Redistributing data we lack rights to", "Legal", "Possible", "Moderate", "Medium",
         "Licence gate: redistributable ∧ licence_reviewed (decision D4)", "Low", "TBC", "Open"],
        ["R05", "No Art 28 processor agreement between IF and R1X", "Legal", "Certain", "Moderate", "High",
         "Execute written agreement — live gap today, not only for this platform", "Low", "TBC", "**Open**"],
        ["R06", "Immutable releases cannot honour erasure requests", "Legal", "Possible", "Major", "High",
         "Anonymise the gold layer so UK GDPR does not apply to published files", "Low", "TBC", "Open"],
        ["R07", "NER misses names in free text", "Privacy", "Likely", "Major", "High",
         "Defence in depth: regex + NER + gazetteer + k-anonymity + sampled human review", "Medium", "TBC", "Open"],
        ["R08", "Nameserver migration breaks info@inno-forum.co.uk", "Operational", "Possible", "Major", "High",
         "Launch on workers.dev; migrate DNS only under supervision", "Low", "TBC", "Open"],
    ]
    ws = sheet(
        wb, "Risk Register", "Risk Register (ISO 31000)",
        "HUMAN JUDGEMENT — preserved across regeneration. Seeded from the compliance design; ratings and "
        "owners need confirming by the accountable person.",
        ["ID", "Risk", "Category", "Likelihood", "Impact", "Inherent", "Mitigation", "Residual", "Owner", "Status"],
        risks,
    )
    ws["A2"].fill = WARN_FILL

    # ---------------- 10. Change Log (preserved) ----------------
    log = list(preserved.get("Change Log") or [])
    # Append a regeneration entry, but only once per day per catalogue state — otherwise
    # every run adds a near-identical row and the log stops being readable.
    cat_sha = hashlib.sha256("".join(c["_sha"] for c in cats).encode()).hexdigest()[:8]
    entry = [today, "Register regenerated", f"Catalogue state {cat_sha}", "build-data-register.py"]
    if not any(r[:1] == [today] and len(r) > 2 and r[2] == entry[2] for r in log):
        log.append(entry)
    sheet(
        wb, "Change Log", "Change Log",
        "Append-only. Preserved across regeneration so the register is auditable over time.",
        ["Date", "Change", "Detail", "By"], log,
    )
    return wb


def read_preserved(path: Path) -> dict[str, list[list]]:
    """Read judgement sheets from an existing workbook so regeneration never destroys them."""
    if not path.exists():
        return {}
    wb = load_workbook(path)
    out: dict[str, list[list]] = {}
    for name in PRESERVED:
        if name not in wb.sheetnames:
            continue
        ws = wb[name]
        rows = []
        for r in ws.iter_rows(min_row=5, values_only=True):
            if r and any(v not in (None, "") for v in r):
                rows.append(list(r))
        if rows:
            out[name] = rows
    return out


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--out", help="output .xlsx path")
    ap.add_argument("--evidence", help="k-anonymity evidence JSON (from build/kanon.py --json)")
    ap.add_argument("--check", action="store_true", help="read-only: report what would change")
    args = ap.parse_args()

    cats = load_catalogues()
    if not cats:
        sys.exit("No catalogues found.")

    evidence = {}
    if args.evidence and Path(args.evidence).exists():
        raw = json.loads(Path(args.evidence).read_text())
        evidence = raw if isinstance(raw, dict) else {}

    if args.check:
        print(f"Catalogues: {len(cats)}")
        for c in cats:
            n_ind = sum(1 for t in c.get("gold_tables", []) if t.get("contains_individuals"))
            flag = " ← contains individuals" if n_ind else ""
            print(f"  {c['challenge']}: {len(c.get('gold_tables', []))} table(s), "
                  f"{len(c.get('sources', []))} source(s){flag}")
        missing = [f"{c['challenge']}/{t['name']}"
                   for c in cats for t in c.get("gold_tables", [])
                   if t.get("contains_individuals") and f"{c['challenge']}/{t['name']}" not in evidence]
        if missing:
            print("\nNOT EVIDENCED (must not be published):")
            for m in missing:
                print(f"  • {m}")
            return 1
        return 0

    if not args.out:
        sys.exit("--out is required (or use --check)")

    out = Path(args.out)
    preserved = read_preserved(out)
    if preserved:
        print(f"Preserving {len(preserved)} judgement sheet(s): {', '.join(preserved)}")

    wb = build(cats, evidence, preserved)
    out.parent.mkdir(parents=True, exist_ok=True)
    wb.save(out)

    print(f"\nWrote {out}")
    print(f"  {len(wb.sheetnames)} sheets: {', '.join(wb.sheetnames)}")
    print(f"  derived (regenerated): {', '.join(DERIVED)}")
    print(f"  preserved (judgement): {', '.join(PRESERVED)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
